server:
  max-http-request-header-size: 400000
spring:
  config:
    import:
      - classpath:/application-dev.yml
      - classpath:/application-oauth.yml
      - classpath:/application-s3.yml
#  profiles:
#    active: dev, oauth, s3