spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    hikari:
      username: ssafy
      password: ssafy123~
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
